version: '3.6'
services:
  php:
    image: sunthera/taktik:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    entrypoint:
      - bash
      - /taktik/php/entrypoint.sh
    command:
      - php-fpm
    volumes:
      - code:/app
      - ~/.config/composer/auth.json:/var/www/.composer/auth.json:ro
      - ${PWD}/taktik/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ${PWD}/taktik/php/conf.d/zz-application.ini:/usr/local/etc/php/conf.d/zz-application.ini:ro
      - ${PWD}/taktik/php/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf:ro
      - ${PWD}/taktik/php/entrypoint.sh:/taktik/php/entrypoint.sh:ro
    ports:
      - 2222:2222
    networks:
      default:
        aliases:
          - php.taktik.internal
  
  nginx:
    image: nginx:1.21
    volumes:
      - code:/app

volumes:
  code:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: ${PWD}/.
