version: '3.6'
services:
  redis-two:
    image: redis:6
    command:
      - 'redis-server'
      - '--loglevel notice'
      - '--databases 1'
      - '--maxmemory 128mb'
      - '--maxmemory-policy volatile-lru'
      - '--bind 0.0.0.0'
    volumes:
      - redis-one:/data

volumes:
  redis-one:
