version: '3'

silent: true

dotenv:
  - ".taktik"
  - ".taktik.local"

vars:
  COMPOSE_BINARY: '{{.COMPOSE_BINARY | default "docker-compose"}}'
  COMPOSE_OPTIONS: '{{.COMPOSE_OPTIONS}}'
  COMPOSE_COMMAND_STUB: "{{.COMPOSE_BINARY}} {{.COMPOSE_OPTIONS}}"

tasks:

  default:
    cmds:
      - task -l

  up: 
    desc: "Start containers"
    cmds:
      - "{{.COMPOSE_COMMAND_STUB}} up {{.COMMAND_OPTIONS}}"
    vars:
      COMMAND_OPTIONS: "{{.UP_OPTIONS}} {{.CLI_ARGS}}"

  down:
    desc: "Stops containers."
    cmds:
      - "{{.COMPOSE_COMMAND_STUB}} down {{.COMMAND_OPTIONS}}"
    vars:
      COMMAND_OPTIONS: "{{.DOWN_OPTIONS}} {{.CLI_ARGS}}"
  
  build:
    desc: "Build or rebuild services."
    cmds:
      - "{{.COMPOSE_COMMAND_STUB}} build {{.COMMAND_OPTIONS}}"
    vars:
      COMMAND_OPTIONS: "{{.BUILD_OPTIONS}} {{.CLI_ARGS}}"

  rebuild:
    desc: "Rebuild containers: down, build. up"
    cmds:
      - task: down
      - task: build
      - task: up

  logs:
    desc: "View output from containers."
    cmds:
      - "{{.COMPOSE_COMMAND_STUB}} logs {{.COMMAND_OPTIONS}}"
    vars:
      COMMAND_OPTIONS: "{{.LOGS_OPTIONS}} {{.CLI_ARGS}}"
  
  exec:
    desc: Execute a command in a running container
    cmds:
      - "{{.COMPOSE_COMMAND_STUB}} exec {{.COMMAND_OPTIONS}}"
    vars:
      COMMAND_OPTIONS: "{{.EXEC_OPTIONS}} {{.CLI_ARGS}}"
